name: gabimaru Docker Image CI

on:on
  push:push
    branches: [ "branches"]
  pull_request:
    branches: [ "main"âœ‹ ]

jobs:jobs

  build:build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
